version: "3.0"
services:
  backend:
    image: "test_local_laravel"
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        APP_NAME: ${APP_NAME}
        APP_PORT: ${APP_PORT}
        TZ: ${TZ}
        PHP_VERSION: ${PHP_VERSION}
        UNAME: ${UNAME}
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "2525:2525"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - "../${APP_NAME}:/var/www/html"
    
    networks:
      - servicesNetwork
  dbserver:
    image: mysql:8.0
    ports:
    - "${DB_SERVER_PORT}:${DB_SERVER_PORT}"
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_TCP_PORT=${DB_SERVER_PORT}
    restart: unless-stopped
    volumes:
      - db-test-volume26:/var/lib/mysql
    networks:
      - servicesNetwork
networks:
  servicesNetwork:
volumes:
  db-test-volume26: