version: "3.0"
services:
  backend:
    image: "local_laravel10"
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        APP_NAME: ${APP_NAME}
        APP_PORT: ${APP_PORT}
        TZ: ${TZ}
        NODE_VERSION: ${NODE_VERSION}
        PHP_VERSION: ${PHP_VERSION}
        UNAME: ${UNAME}
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "2525:2525"
#      - "9002:9002"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - "../${APP_NAME}:/app"
    
    networks:
      - servicesNetwork
  dbserver:
    image: mysql:5.7
    ports:
    - "${DB_SERVER_PORT}:${DB_SERVER_PORT}"
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_TCP_PORT=${DB_SERVER_PORT}
    restart: unless-stopped
    volumes:
      - ./dbfiles:/var/lib/mysql
    networks:
      - servicesNetwork
networks:
  servicesNetwork: