#!/usr/bin/env bash

sudo composer create-project laravel/laravel .

sudo npm update
sudo npm install
sudo npm run build

sudo chown -R $USERNAME /app

php artisan serve --host=0.0.0.0 --port=$APP_PORT