#!/usr/bin/env bash

apt install php$PHP_VERSION-xdebug

echo "xdebug.mode=debug"  >> /etc/php/$PHP_VERSION/cli/conf.d/20-xdebug.ini
echo "xdebug.start_with_request=yes"  >> /etc/php/$PHP_VERSION/cli/conf.d/20-xdebug.ini
echo "xdebug.client_host=host.docker.internal"  >> /etc/php/$PHP_VERSION/cli/conf.d/20-xdebug.ini
echo "xdebug.remote_enable=off"  >> /etc/php/$PHP_VERSION/cli/conf.d/20-xdebug.ini
echo "xdebug.discover_client_host=1"  >> /etc/php/$PHP_VERSION/cli/conf.d/20-xdebug.ini
echo "xdebug.remote_port=9003"  >> /etc/php/$PHP_VERSION/cli/conf.d/20-xdebug.ini